//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVModel
{
    using System;
    using System.Collections.Generic;

    public partial class tbl_chuyennganhEntity
    {
        public int Macn { get; set; }
        public string Tencn { get; set; }
        public string Ghichu { get; set; }
    }

    public partial class tbl_chuyennganh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_chuyennganh()
        {
            this.tbl_sinhvien = new HashSet<tbl_sinhvien>();
        }
    
        public int Macn { get; set; }
        public string Tencn { get; set; }
        public string Ghichu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sinhvien> tbl_sinhvien { get; set; }
    }
}
