//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVModel
{
    using System;
    using System.Collections.Generic;

    public partial class tbl_sinhvienEntity
    {
        public int Masv { get; set; }
        public string TenSV { get; set; }
        public Nullable<System.DateTime> Namsinh { get; set; }
        public Nullable<bool> Gioittinh { get; set; }
        public string Khoa { get; set; }
        public string Chuyennganh { get; set; }
        public string Email { get; set; }
        public string Dienthoai { get; set; }
        public string Diachi { get; set; }
        public Nullable<bool> Totnghiep { get; set; }

        public virtual tbl_chuyennganh tbl_chuyennganh { get; set; }
        public virtual tbl_khoahoc tbl_khoahoc { get; set; }
    }

    public partial class tbl_sinhvien
    {
        public int Masv { get; set; }
        public string TenSV { get; set; }
        public DateTime Namsinh { get; set; }
        public bool Gioittinh { get; set; }
        public int Khoa { get; set; }
        public int Chuyennganh { get; set; }
        public string Email { get; set; }
        public string Dienthoai { get; set; }
        public string Diachi { get; set; }
        public bool Totnghiep { get; set; }
    
        public virtual tbl_chuyennganh tbl_chuyennganh { get; set; }
        public virtual tbl_khoahoc tbl_khoahoc { get; set; }
    }
}
